-- Seed data for Ahsan Project. Generated from app/lib/seed.ts —
-- run `node --experimental-strip-types scripts/generate-seed-sql.mjs` after editing it.

INSERT OR IGNORE INTO `users` (`id`, `username`, `name`, `email`, `headline`, `bio`, `website`, `github`) VALUES ('seed-zikrul', 'zikrulihsan', 'Zikrul Ihsan', '', 'Bikin barang kecil yang kepakai', 'Mengerjakan proyek satu per satu di waktu luang. Ahsan artinya melakukan sesuatu sebaik mungkin — itu yang saya usahakan di sini, sekecil apa pun yang sedang dikerjakan.', 'https://ahsanproject-id.netlify.app', 'https://github.com/zikrulihsan');

--> statement-breakpoint

INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (1, 'tap-tap-dzikr', 'Tap Tap Dzikr', 'Ganti kebiasaan tap tap medsos dengan tap tap dzikir.', 'seed-zikrul', 'live', 'Jempol kita sudah terlatih untuk tap dan scroll tanpa sadar, dan medsos yang paling gampang diraih. Niat berdzikir sering kalah cepat dari kebiasaan itu, apalagi kalau harus cari tasbih dulu atau menghitung di kepala sambil mengerjakan hal lain.', 'Penghitung dzikir harian yang sesederhana mungkin: buka, tap, selesai. Tidak ada akun, tidak ada notifikasi yang mengejar, tidak ada angka yang bikin merasa bersaing. Hitungannya tersimpan di perangkat sendiri supaya bisa dilanjutkan besok.', 'Siapa pun yang ingin memindahkan kebiasaan tap tap-nya ke hal yang lebih menenangkan.', '', 'https://dzikir-harian.netlify.app/', '', 'ibadah,kebiasaan,mobile', 'mint', '○○○', '2024-05-04 09:00:00', '2024-05-04 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (1, 1, 'design', 'Menata ulang tampilan penghitungnya supaya nyaman dipakai satu tangan, termasuk mode gelap.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (2, 'wecard', 'Wecard', 'Kartu pertanyaan untuk obrolan yang tidak berhenti di basa-basi.', 'seed-zikrul', 'live', 'Ngobrol sama orang terdekat sering mentok di pertanyaan yang itu-itu saja: sudah makan, gimana kerjaan, kapan nikah. Yang ingin ditanyakan sebenarnya lebih dalam dari itu, tapi tidak ada yang mau memulai duluan karena takut kaku.', 'Kumpulan kartu berisi pertanyaan yang sudah disusun per situasi — teman, keluarga, pasangan. Tinggal buka satu kartu dan biarkan pertanyaannya yang memulai, jadi tidak ada yang perlu merasa canggung sebagai orang pertama.', 'Teman, keluarga, atau pasangan yang ingin ngobrol lebih dalam tanpa harus tahu cara memulainya.', '', 'https://wecard-app.netlify.app/', '', 'obrolan,relasi,kartu', 'yellow', '▱', '2024-07-18 09:00:00', '2024-07-18 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (2, 2, 'content', 'Menulis satu dek baru untuk obrolan rekan kerja, sekitar 40 pertanyaan.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (3, 'carikontak', 'CariKontak', 'Nomor penting di sekitarmu, siap saat benar-benar dibutuhkan.', 'seed-zikrul', 'live', 'Saat ada yang mendesak — genteng bocor, motor mogok, butuh ambulans — waktu justru habis untuk mencari nomor. Kontak tukang, bengkel, atau layanan darurat biasanya tersebar di chat lama, catatan, atau ingatan orang lain.', 'Tempat menyimpan dan mencari kontak penting berdasarkan wilayah, jadi nomornya sudah ada sebelum dibutuhkan. Datanya bisa ditambah bersama-sama supaya satu daerah saling menolong lewat daftar yang sama.', 'Warga yang ingin punya daftar nomor penting daerahnya di satu tempat.', '', 'https://carikontak.com/', '', 'warga,direktori,lokal', 'blue', '⌖', '2024-09-02 09:00:00', '2024-09-02 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (3, 3, 'growth', 'Mengajak komunitas RT/RW di satu kota untuk mengisi datanya lebih dulu.', 'open', NULL, '');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (4, 3, 'engineering', 'Menambah pencarian berdasarkan jarak dan penyaringan per kecamatan.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (4, 'invoice-cepat', 'Invoice Cepat', 'Bikin invoice untuk jasa atau produkmu tanpa proses berbelit.', 'seed-zikrul', 'live', 'Pelaku usaha kecil sering menagih lewat chat karena aplikasi invoice yang ada terasa berat: harus daftar, isi profil perusahaan, pilih paket. Untuk satu tagihan sederhana, semua itu terlalu banyak langkah.', 'Formulir singkat yang langsung menghasilkan invoice rapi dan bisa dibagikan. Tanpa akun, tanpa langganan, cukup isi yang perlu lalu kirim ke pelanggan.', 'Freelancer dan pemilik usaha kecil yang menagih beberapa kali sebulan.', '', 'https://umkmproject-invoice.netlify.app/', '', 'umkm,keuangan,tools', 'coral', '≡', '2024-11-11 09:00:00', '2024-11-11 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (5, 4, 'pm', 'Menentukan fitur berikutnya dari keluhan pengguna yang sudah masuk.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (5, 'main-aman', 'Main Aman', 'Tempat belajar anak supaya lebih siap menjaga diri.', 'seed-zikrul', 'live', 'Anak-anak diminta hati-hati, tapi jarang diberi contoh situasinya seperti apa. Orang tua juga sering bingung memulai obrolan soal batas tubuh, orang asing, atau situasi yang bikin tidak nyaman.', 'Materi belajar yang dikemas ringan dan bisa dibuka bersama orang tua, berisi situasi sehari-hari beserta apa yang sebaiknya dilakukan anak. Bahasanya dibuat sederhana supaya anak bisa mengulang sendiri.', 'Anak usia sekolah dasar bersama orang tua atau gurunya.', '', 'https://mainaman.netlify.app/', '', 'anak,edukasi,keamanan', 'purple', '✦', '2025-01-20 09:00:00', '2025-01-20 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (6, 5, 'research', 'Menguji materinya ke satu kelas dan merapikan bagian yang belum kena.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (6, 'swegrowth', 'Swegrowth', 'Portal komunitas software engineer Indonesia.', 'seed-zikrul', 'live', 'Pengalaman berharga teman-teman engineer di Indonesia berserak di utas media sosial dan grup chat yang tenggelam dalam hitungan hari. Yang baru mulai kesulitan menemukannya lagi saat benar-benar butuh.', 'Satu portal tempat cerita, materi belajar, dan pengalaman kerja dikumpulkan supaya bisa dibaca ulang kapan pun. Isinya datang dari komunitas, bukan dari satu orang saja.', 'Software engineer Indonesia, terutama yang sedang di tahun-tahun awal.', '', 'https://swegrowth.id/', '', 'komunitas,karier,belajar', 'green', '↗', '2025-03-08 09:00:00', '2025-03-08 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (7, 6, 'content', 'Mengurasi dan menyunting tulisan kiriman komunitas tiap bulan.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (7, 'warung-antre', 'Warung Antre', 'Antrean digital untuk warung dan kedai kecil yang ramai di jam makan.', 'seed-zikrul', 'idea', 'Di jam makan siang, warung kecil ramai dan pesanan diingat di kepala. Pembeli menunggu tanpa tahu urutannya di mana, penjual repot menghafal, dan yang datang belakangan kadang malah dilayani duluan. Ributnya kecil tapi terjadi setiap hari.', 'Nomor antrean yang dibuat cukup lewat satu layar di warung: pembeli memindai kode, penjual menggeser antrean saat pesanan siap. Tidak perlu perangkat tambahan, tidak perlu pelatihan, dan tetap jalan kalau sinyalnya jelek.', 'Warung, kedai kopi, dan gerai kecil yang ramai pada jam tertentu.', '', '', '', 'umkm,operasional,ide', 'sand', '◔', '2025-06-14 09:00:00', '2025-06-14 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (8, 7, 'research', 'Ngobrol dengan lima pemilik warung untuk memastikan masalahnya memang terasa.', 'open', NULL, '');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (9, 7, 'design', 'Membuat alur layar penjual yang bisa dipakai sambil tangan sibuk.', 'open', NULL, '');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (10, 7, 'engineering', 'Prototipe antrean yang tetap jalan saat koneksi putus.', 'open', NULL, '');
INSERT OR IGNORE INTO `projects` (`id`, `slug`, `title`, `tagline`, `owner_id`, `stage`, `problem`, `solution`, `audience`, `doc_url`, `live_url`, `repo_url`, `tags`, `accent`, `glyph`, `created_at`, `updated_at`) VALUES (8, 'titip-jemput', 'Titip Jemput', 'Papan koordinasi antar-jemput sekolah antar orang tua satu kompleks.', 'seed-zikrul', 'validating', 'Orang tua di satu kompleks sering menjemput ke sekolah yang sama pada jam yang sama, tapi tetap berangkat sendiri-sendiri. Koordinasinya nyangkut di grup chat: pesan tenggelam, yang butuh tumpangan sungkan minta, yang punya kursi kosong tidak tahu siapa yang butuh.', 'Papan sederhana berisi jadwal jemput mingguan: siapa berangkat jam berapa, ke sekolah mana, ada berapa kursi kosong. Orang tua tinggal menandai butuh atau menawarkan, tanpa perlu menawar di grup ramai.', 'Orang tua di satu kompleks atau perumahan dengan sekolah tujuan yang sama.', '', '', '', 'keluarga,komunitas,ide', 'sky', '⌁', '2025-08-01 09:00:00', '2025-08-01 09:00:00');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (11, 8, 'pm', 'Merapikan alurnya jadi sesederhana mungkin supaya tidak kalah praktis dari grup chat.', 'open', NULL, '');
INSERT OR IGNORE INTO `seats` (`id`, `project_id`, `role`, `brief`, `status`, `user_id`, `pitch`) VALUES (12, 8, 'design', 'Menyusun tampilan papan mingguan yang kebaca sekali lihat.', 'open', NULL, '');
